### ISSUE TITLE
Enhancement: show dates for holidays

### ISSUE THREAD

**Issue by fabioelia** [f1v/hrbot#173] opened 2021-06-18 15:30 UTC
**Summary**
Provide dates on holidays
![image](https://user-images.githubusercontent.com/633247/122584592-898e3680-d028-11eb-81fc-f02c84ce33cd.png)

**Impact**
_What audience is this feature for? What is its impact_

**Acceptance Criteria**

1.
2.
3.

**Time Estimation (in hours)**

```
1
```

**Checklist**

- [ ] Feature must have associated Milestone
- [ ] Feature must have associated Project if PR is merged
- [ ] Feature must be one of three types below

#### Feature Types and Definitions

```
Feature - A small or medium sized change that adds new functionality
Enhancement - A small change that adds new functionality to an existing feature
Big Feature - A big sized change that is loosely described that is completely new
```

**Comment by davidholyko** [comment] 2021-06-18 16:27
Duplicate of: https://github.com/f1v/hrbot/issues/64

Related to: https://github.com/f1v/hrbot/issues/48

**Closed** 2021-06-18 18:21 UTC
